============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /root/projects/qvm
plugins: anyio-3.6.2
collected 11 items / 10 deselected / 1 selected

tst/qvm/integration/qvm_test.py 
==== Testing ===

==== qasm_list ===

/root/projects/QASMBench/small//hhl_n10/hhl_n10.qasm,/root/projects/QASMBench/small//bb84_n8/bb84_n8.qasm
compute_unit_list	[{0, 10, 4}, {3, 6}]
naive selection time	5.14984130859375e-05
F

=================================== FAILURES ===================================
_ TestSelectMethods.test_naive_reverse_select[/root/projects/QASMBench/small//hhl_n10/hhl_n10.qasm,/root/projects/QASMBench/small//bb84_n8/bb84_n8.qasm-FakeBrooklyn-4] _

self = <qvm_test.TestSelectMethods object at 0x7f534ca9cd30>
qasm = '/root/projects/QASMBench/small//hhl_n10/hhl_n10.qasm,/root/projects/QASMBench/small//bb84_n8/bb84_n8.qasm'
backend = 'FakeBrooklyn', cu_size = '4'

    def test_naive_reverse_select(self, qasm, backend, cu_size):
        """
        Test brute_force and naive method
    
        Args:
            bench: List of qasm file paths
            backend: Backend name
        """
    
        self.prepare_for_test(qasm, backend, cu_size)
    
        # Naive reverse
        st_time = time.time()
        naive_exes = self.proc_manager._select_naive(self.process_list, reverse=True)
        self.debug_exes(naive_exes)
        print(f"naive selection time\t{time.time() - st_time}")
        naive_exes = self.reconstruct_exes(naive_exes, self.process_list)
>       fid = self.get_fidelity(self.circuit_list, naive_exes)

tst/qvm/integration/qvm_test.py:259: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tst/qvm/integration/qvm_test.py:161: in get_fidelity
    res = exe.comp_unit.backend.run(exe.circ, shots=shots).result().get_counts()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = Result(backend_name='aer_simulator', backend_version='0.11.0', qobj_id='de199312-2c28-4361-b804-a7f74b32dc62', job_id=...taken_load_qobj': 0.991679958, 'num_processes_per_experiments': 1, 'omp_enabled': True}, time_taken=1.0261645317077637)
experiment = None

    def get_counts(self, experiment=None):
        """Get the histogram data of an experiment.
    
        Args:
            experiment (str or QuantumCircuit or Schedule or int or None): the index of the
                experiment, as specified by ``data([experiment])``.
    
        Returns:
            dict[str, int] or list[dict[str, int]]: a dictionary or a list of
            dictionaries. A dictionary has the counts for each qubit with
            the keys containing a string in binary format and separated
            according to the registers in circuit (e.g. ``0100 1110``).
            The string is little-endian (cr[0] on the right hand side).
    
        Raises:
            QiskitError: if there are no counts for the experiment.
        """
        if experiment is None:
            exp_keys = range(len(self.results))
        else:
            exp_keys = [experiment]
    
        dict_list = []
        for key in exp_keys:
            exp = self._get_experiment(key)
            try:
                header = exp.header.to_dict()
            except (AttributeError, QiskitError):  # header is not available
                header = None
    
            if "counts" in self.data(key).keys():
                if header:
                    counts_header = {
                        k: v
                        for k, v in header.items()
                        if k in {"time_taken", "creg_sizes", "memory_slots"}
                    }
                else:
                    counts_header = {}
                dict_list.append(Counts(self.data(key)["counts"], **counts_header))
            elif "statevector" in self.data(key).keys():
                vec = postprocess.format_statevector(self.data(key)["statevector"])
                dict_list.append(statevector.Statevector(vec).probabilities_dict(decimals=15))
            else:
>               raise QiskitError(f'No counts for experiment "{repr(key)}"')
E               qiskit.exceptions.QiskitError: 'No counts for experiment "0"'

/root/anaconda3/envs/qcs-noise/lib/python3.10/site-packages/qiskit/result/result.py:289: QiskitError
------------------------------ Captured log call -------------------------------
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 26, current visited status: {0, 1, 3, 4, 5, 6, 8, 10, 12, 13, 18, 19, 20, 21, 22, 23, 25, 26, 34, 35, 36, 37, 42, 43, 44, 45, 49, 50, 51, 54}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 26'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 40, current visited status: {0, 1, 3, 4, 5, 6, 8, 10, 12, 13, 18, 19, 20, 21, 22, 25, 26, 34, 35, 36, 37, 40, 42, 43, 44, 45, 49, 50, 51, 54}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 40'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 9, current visited status: {0, 1, 3, 4, 5, 6, 8, 9, 10, 12, 13, 18, 19, 20, 21, 22, 25, 26, 27, 28, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 49, 50, 51, 52, 54, 55, 56, 57}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 9'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 7, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 7'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 62, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 62'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 16, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 16'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 23, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 23'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 17, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 17'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 63, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 63'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 64, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 64'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 11, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 11'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 33, current visited status: {0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 33'
WARNING  root:graph.py:571 Failed to grow a subgraph from root: 2, current visited status: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64}, error message is 'Cannot grow a graph that satisfy the subgraph size from current root: 2'
=============================== warnings summary ===============================
qcs/tst/qvm/integration/qvm_test.py::TestSelectMethods::test_naive_reverse_select[/root/projects/QASMBench/small//hhl_n10/hhl_n10.qasm,/root/projects/QASMBench/small//bb84_n8/bb84_n8.qasm-FakeBrooklyn-4]
  /root/anaconda3/envs/qcs-noise/lib/python3.10/site-packages/qiskit/providers/fake_provider/fake_backend.py:462: PendingDeprecationWarning: "warnings" argument will be deprecated as part of the qiskit-aer 0.12.0 and subsequently removed
    noise_model = NoiseModel.from_backend(self, warnings=False)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tst/qvm/integration/qvm_test.py::TestSelectMethods::test_naive_reverse_select[/root/projects/QASMBench/small/hhl_n10/hhl_n10.qasm,/root/projects/QASMBench/small/bb84_n8/bb84_n8.qasm-FakeBrooklyn-4]
============ 1 failed, 10 deselected, 1 warning in 64.47s (0:01:04) ============
